% Auto-generated by cameraCalibrator app on 14-Sep-2017
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_3.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_5.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_6.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_8.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_9.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_11.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_12.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_13.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_14.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_15.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_16.png',...
    '/Users/Clay/Desktop/Fisheye Correction/onPlane/on_plane_17.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 6;  % in units of 'in'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'in', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);


% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{7});
[undistortedImage, newOrigin] = undistortImage(originalImage, cameraParams, 'OutputView', 'full');
points = detectCheckerboardPoints(imageFileNames{7});
undistortedPoints = undistortPoints(points, cameraParams);
undistortedPoints = [undistortedPoints(:,1) - newOrigin(1), ...
                    undistortedPoints(:,2) - newOrigin(2)];
                
                
figure(100);clf;
subplot(1,2,1);
imshow(originalImage);
title('Original');

figure(100);
subplot(1,2,2);
imshow(undistortedImage);
title('Undistorted');